sems: prod_cons-sems-cs23btech11021.cpp
	g++ prod_cons-sems-cs23btech11021.cpp -o sems
locks:prod_cons-locks-cs23btech11021.cpp
	g++ prod_cons-locks-cs23btech11021.cpp -o locks
clean:
	rm -rf sems locks
